name: Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./Frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./Frontend

      # Copy frontend build to backend public directory
      - name: Copy frontend build to backend
        run: |
          rm -rf ./Backend/server/public
          mkdir -p ./Backend/server/public
          cp -r ./Frontend/dist/* ./Backend/server/public/

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: ./Backend/server

      # Prepare for deployment (production dependencies only)
      - name: Prepare for deployment
        run: |
          rm -rf node_modules
          npm ci --only=production
        working-directory: ./Backend/server

      # Zip for deployment
      - name: Zip artifact for deployment
        run: |
          cd Backend/server
          zip -r ../../release.zip ./*

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip

# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples
